name: curl for Win64 and msvc

on:
  push:
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Download curl
      run: |
        - (new-object System.Net.WebClient).DownloadFile( 'https://curl.haxx.se/download/curl-7.70.0.zip', 'c:\temp\curl-7.70.0.zip')
        - dir c:\temp\curl7700.zip    
          
    - name: Build curl using msvc
      shell: cmd 
      run: |
        - cd c:\temp\curl-7.70.0\winbuild\
        - set MACHINE=x64
        - nmake /f Makefile.vc mode=static
