name: curl for Win64 and msvc

on:
  push:
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Download curl
      run: |
        (new-object System.Net.WebClient).DownloadFile( 'https://curl.haxx.se/download/curl-7.70.0.zip', 'c:\temp\curl-7.70.0.zip')
        Expand-Archive -LiteralPath 'c:\temp\curl-7.70.0.zip' -DestinationPath 'curl-7.70.0' -Force  
  
    - name: Build curl using msvc
      shell: cmd 
      run: |
        cd curl-7.70.0\curl-7.70.0\winbuild
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        set MACHINE=x64
        nmake /f Makefile.vc mode=static
        cd ..
        dir -s build
        
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD
 
    - name: Upload curl_win64_msvc to artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: modharbour_win64_msvc_${{ env.TIME }}
       path: build
