name: curl for Win64 and msvc using vcpkg

on:
  push:
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
  
    - name: Installing dependencies
      shell: cmd 
      run: |
        vcpkg.exe install curl
        vcpkg.exe install openssl
        dir 
        
