name: curl for Win64 and msvc using vcpkg

on:
  push:
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
  
    - name: Using vcpkg to get curl
      shell: cmd 
      run: |
        vcpkg.exe install curl
        
