name: Harbour for Win64 using msvc

on:
  push:
  watch:
   types: [started]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: checking vcpkg
        shell: cmd 
        run: |
          vcpkg.exe list
        
